// scripts/native/build-www.mjs [--env=prod|staging|dev]
// Assembles www/ for the Capacitor shell from the buildless web app:
//   1. copies the static site (allowlist) into www/
//   2. writes www/native-env.js  (forces the Firebase env + marks the native shell)
//   3. bundles native/bridge.js → www/native-bridge.js (esbuild, IIFE)
//   4. patches www/index.html: viewport-fit=cover + the two native scripts
// The web deploy (GitHub Pages) never sees any of this — www/ is git-ignored.
import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { execSync } from 'node:child_process';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('../../', import.meta.url));
const outArg = process.argv.find(a => a.startsWith('--out='));
const OUT = outArg ? outArg.slice(6) : join(ROOT, 'www');   // --out= is for tests only
const envArg = process.argv.find(a => a.startsWith('--env='));
const ENV = envArg ? envArg.slice(6) : 'prod';
if (!['dev', 'staging', 'prod'].includes(ENV)) { console.error(`bad --env=${ENV}`); process.exit(2); }

// Files/dirs that make up the runnable site. Everything else (docs, scripts,
// scratch screenshots, functions, node_modules) stays out of the app bundle.
const ALLOW = ['index.html', 'privacy.html', 'terms.html', 'cookies.html', 'manifest.json', 'favicon.svg', 'css', 'js', 'assets'];
const EXCLUDE_DIRS = new Set([join(ROOT, 'assets', 'generated')]);

rmSync(OUT, { recursive: true, force: true });
mkdirSync(OUT, { recursive: true });
for (const item of ALLOW) {
  const src = join(ROOT, item);
  if (!existsSync(src)) { console.warn(`  (missing, skipped) ${item}`); continue; }
  cpSync(src, join(OUT, item), { recursive: true, filter: (s) => !EXCLUDE_DIRS.has(s) });
}

// 2. env + shell marker (must run before any module script)
writeFileSync(join(OUT, 'native-env.js'),
  `// generated by scripts/native/build-www.mjs — do not edit\nwindow.__TOMODACHI_ENV__ = ${JSON.stringify(ENV)};\nwindow.__TOMODACHI_NATIVE__ = true;\n`);

// 3. bridge bundle
execSync(`node "${join(ROOT, 'scripts', 'native', 'build-bridge.mjs')}"`, { stdio: 'inherit', env: { ...process.env, WWW_OUT: OUT } });

// 4. patch index.html (idempotent: keeps whatever viewport the site ships,
//    only appends viewport-fit=cover when absent)
const idx = join(OUT, 'index.html');
let html = readFileSync(idx, 'utf8');
html = html.replace(/<meta name="viewport" content="([^"]*)">/, (m, content) =>
  content.includes('viewport-fit=cover') ? m : `<meta name="viewport" content="${content}, viewport-fit=cover">`);
if (!html.includes('native-env.js')) {
  html = html.replace('<head>', '<head>\n  <script src="native-env.js"></script>\n  <script src="native-bridge.js" defer></script>');
}
writeFileSync(idx, html);
console.log(`www/ built for env=${ENV} (${ALLOW.length} roots) → ${OUT}`);
